---
- name: Check Ports
  hosts: Routers
  connection: network_cli

  tasks:
    - name: Check ports
      ios_command:
        commands:
          - "Show ip interface brief {{ interface }}"
      register: var_ip_addr

    - name: Check if IP address is assigned
      when: var_ip_addr.stdout[0] | length > 0
      assert:
        that:
          - var_ip_addr.stdout[1] | length > 0
          - var_ip_addr.stdout[1].split()[1] | ipaddr

    - name: Check if interface is up
      when: var_ip_addr.stdout[0] | length > 0
      ios_command:
        commands:
          - "sh int br {{ interface }}"
      register: var_int_status

    - name: Assert interface is up
      when: var_ip_addr.stdout[0] | length > 0
      assert:
        that:
          - var_int_status.stdout[0] | length > 0
          - var_int_status.stdout[0].split()[0] in ["up", "administratively"]

    - name: Send notification if interface is down
      debug:
        msg: "The interface {{ interface }} on the router {{ ansible_hostname }} is down."
      when: var_ip_addr.stdout[0] | length > 0 and (var_int_status.stdout[0] | length == 0 or var_int_status.stdout[0].split()[0] not in ["up", "administratively"])
