---
- name: Check Cisco Routers
  hosts: routers
  gather_facts: no
  vars:
    ansible_connection: ssh

  tasks:
    - name: Check IP address for all interfaces
      ios_command:
        commands:
          - "show ip interface brief"
      register: ip_check

    - name: Extract interface information
      set_fact:
        interface_info: "{{ ip_check.stdout[0] | regex_findall('([A-Za-z]+[0-9]+/[0-9]+)') }}"

    - name: Check link status for all interfaces
      ios_command:
        commands: "show interface {{ item }}"
      register: link_status
      loop: "{{ interface_info }}"

    - name: Report interface status
      debug:
        msg: "Interface {{ item.0 }} on router {{ inventory_hostname }} is {{ 'down' if 'down' in item.1 else 'up' }}"
      loop: "{{ link_status.results | zip(interface_info) }}"
