---  # Playbook start

- name: Check Ports
- hosts: Routers
  # ... rest of the tasks
  connection: network_cli
  gather_facts: false

  tasks:
  - name: Check ports
    ios_command:
      commands: 
      - "Show ip interface brief {{ interface }}"
      register: var_ip_addr
  - name: Check if IP address is assigned
    when: var_ip_addr.stdout[0].split('\n')[1].split()[1] != ""
    block:
    - name: Check if IP address is valid
      assert:
        that: var_ip_addr.stdout[0].split('\n')[1].split()[1] | ipaddress
  - name: Check if interface is up
    when: var_ip_addr.stdout[0].split('\n')[1].split()[1] != ""

    ios_command:
      commands:
      - "sh int br {{ interface }}"
    register: var_int_status
  - name: Assert interface is up
    when: var_ip_addr.stdout[0].split('\n')[1].split()[1] != ""
    assert:
      that: var_int_status.stdout[0].split('\n')[1].split()[0] in ["up", "administratively up"]

    notify:
        - Send notification if interface is down

  - name: Send notification if interface is down
    debug:
      msg: "The interface {{ interface }} on the router {{ ansible_hostname }} is down."

  variables:
    interface: "FastEthernet0/1"  # Tilpas interfacenavn
