---
- name: Check Cisco Routers
  hosts: Routers
  connection: network_cli

  tasks:
    - name: Check IP address
      ios_command:
        commands:
          - "show ip interface brief | include {{ interface }}"
      register: ip_check

    - name: Check link status
      ios_command:
        commands:
          - "show interface {{ interface }}"
      register: link_status
      when: ip_check.stdout | length > 0  # Only check link status if IP address is found

    - name: Report interface status
      debug:
        msg: "Interface {{ interface }} on router {{ ansible_host }} is {{ 'down' if 'down' in link_status.stdout else 'up' }}"
      when: ip_check.stdout | length > 0  # Only report if IP address is found
