---  
# Playbook start

variables:
  interface: "GigaEthernet0/0"  # Erstat med dit ønskede interface navn

# Play definition (sørg for korrekt indrykning)
- name: Check Ports  # Beskrivende navn for playet
  hosts: Routers  # Målhosts
  connection: network_cli  # Forbindelsestype

  tasks:
    - name: Check ports
      ios_command:
        commands:
          - "Show ip interface brief {{ interface }}"
      register: var_ip_addr

    - name: Check if IP address is assigned
      when: var_ip_addr.stdout[0].split('\n')[1].split()[1] != ""
      block:
        - name: Check if IP address is valid
          assert:
            that: var_ip_addr.stdout[0].split('\n')[1].split()[1] | ipaddress

    - name: Check if interface is up
      when: var_ip_addr.stdout[0].split('\n')[1].split()[1] != ""
      ios_command:
        commands:
          - "sh int br {{ interface }}"
      register: var_int_status

    - name: Assert interface is up
      when: var_ip_addr.stdout[0].split('\n')[1].split()[1] != ""
      assert:
        that: var_int_status.stdout[0].split('\n')[1].split()[0] in ["up", "administratively up"]
      notify:
        - Send notification if interface is down

    - name: Send notification if interface is down
      debug:
        msg: "The interface {{ interface }} on the router {{ ansible_hostname }} is down."  # Dobbelt citat omkring variabel
      when: var_ip_addr.stdout[0].split('\n')[1].split()[1] != ""
