---
- name: Show Interface Brief
  hosts: router
  gather_facts: no

  vars:
    ansible_connection: network_cli
    ansible_port: 22
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
    ansible_user: admin
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: "cisco"

  tasks:
    - name: Start
      ios_command:
        commands:
          - terminal length 0
          - terminal width 200
          - show license status
      become: true

    - name: Debug connection
      debug:
        msg: "Connecting to {{ inventory_hostname }}"

    - name: Check device state
      cisco.ios.ios_command:
        commands:
          - show privilege
      register: device_state

    - name: Debug device state
      debug:
        var: device_state

    - name: Interface Status
      cisco.ios.ios_facts:
        gather_subset:
          - "!all"
          - "!min"
        gather_network_resources:
          - interfaces
      register: command_output

    - name: Display formatted output
      debug:
        var: command_output

    - name: Run show ip interface brief command
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: show_interface_output

    - name: Debug show ip interface brief output
      debug:
        var: show_interface_output
