---
- ansible_become: true
- ansible_become_method: enable
- hosts: switches
  gather_facts: no

  tasks:
  - name: Configure a vrf named test1
    cisco.ios.ios_vrf:
      name: test1
      description: test
      interfaces:
        - vlan250

  - name: Configure a vrf named test2
    cisco.ios.ios_vrf:
      name: test2
      description: test
      interfaces:
        - vlan260

    handlers:
      - name: save ios
        ios_command:
          commands: "write mem"
          timeout: 40
        when: not ansible_check_mode